### ISSUE TITLE
Feature Request: Link of author

### ISSUE THREAD

**Issue by YunYouJun** [valaxyjs/valaxy-addon-git-log#3]
I think we should add a link `<a href="https://github.com/xxx"` for author `xxx`.

**Comment by WRXinYue** [comment]
This feature has been added. Currently, it only supports retrieving the corresponding user's GitHub homepage link through the `api` mode (i.e., GitHub API). It is not possible to find the GitHub homepage link for these users via the Git method on the Node side. The `GitLogContributor` component currently decides whether to add the `a` tag based on whether the GitHub link is empty.
